# import = ["~/.config/alacritty/gruvbox-dark.toml"]
import = ["~/.config/alacritty/gruvpants.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[window]
# opacity = 0.9
dynamic_title = true

[scrolling]
history = 12000
multiplier = 1

[font]
size = 8

[font.normal]
# family = "firacode"
family = "roboto mono nerd font"
style = "medium"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

